version: '3.8'

services:
  nginx:
    image: nginx:1.17.6-alpine
    container_name: nginx
    ports:
      - "8000:80"

  pg:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
