version: '3.4'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app1
    ports:
      - 3001:8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.6GB'
  app2:
    # <<: *app
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app2
    ports:
      - 3002:8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.6GB'

  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=senha
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.5GB'
  nginx:
    # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      # - app2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'
